"""

Django settings for ProjetCBIR project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see

https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see

https://docs.djangoproject.com/en/5.0/ref/settings/

"""

import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production

# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'django-insecure-)a1jrjmos)e6mc)n$54hm)xw#g09!z^&q$+t4b)&(vn4+__z*&'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [   

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',

    'core_interface', 

    'tailwind',
    'clearcache',

    

]

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    

    'django.middleware.clickjacking.XFrameOptionsMiddleware',


]

ROOT_URLCONF = 'ProjetCBIR.urls'

TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.debug',

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]

WSGI_APPLICATION = 'ProjetCBIR.wsgi.application'

# Database

# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.sqlite3',

        'NAME': BASE_DIR / 'db.sqlite3',

    }

}

# Password validation

# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]

# Internationalization

# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)

# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type

# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = [

    "127.0.0.1",

]

MEDIA_URL = 'core_interface/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'core_interface/media')




FEATURES_VECTORS_PATH_AVGPOOL = os.path.join(BASE_DIR, 'resources/vectors/output_dict_wikiart_avgpool.pt')
FEATURES_VECTORS_PATH_LAYER4 = os.path.join(BASE_DIR, 'resources/vectors/output_dict_wikiart_pca_layer4.pt')
FEATURES_VECTORS_PATH_LAYER3 = os.path.join(BASE_DIR, 'resources/vectors/output_dict_wikiart_pca_layer3.pt')
FEATURES_VECTORS_PATH_LAYER2 = os.path.join(BASE_DIR, 'resources/vectors/output_dict_wikiart_pca_layer2.pt')

PCA_PATH_LAYER4 = os.path.join(BASE_DIR, 'resources/pca_models/output_dict_wikiart_pca_layer4.joblib')
PCA_PATH_LAYER3 = os.path.join(BASE_DIR, 'resources/pca_models/output_dict_wikiart_pca_layer3.joblib')
PCA_PATH_LAYER2 = os.path.join(BASE_DIR, 'resources/pca_models/output_dict_wikiart_pca_layer2.joblib')


FAISS_INDEX_PATH_AVGPOOL = os.path.join(BASE_DIR, 'resources/faiss_indexes/index_faiss.index')
FAISS_INDEX_PATH_LAYER4 = os.path.join(BASE_DIR, 'resources/faiss_indexes/index_faiss_layer4.index')
FAISS_INDEX_PATH_LAYER3 = os.path.join(BASE_DIR, 'resources/faiss_indexes/index_faiss_layer3.index')
FAISS_INDEX_PATH_LAYER2 = os.path.join(BASE_DIR, 'resources/faiss_indexes/index_faiss_layer2.index')

FAISS_MAPPING_PATH_AVGPOOL = os.path.join(BASE_DIR, 'resources/faiss_indexes/index_faiss_mapping.json')
FAISS_MAPPING_PATH_LAYER4 = os.path.join(BASE_DIR, 'resources/faiss_indexes/index_faiss_mapping_layer4.json')
FAISS_MAPPING_PATH_LAYER3 = os.path.join(BASE_DIR, 'resources/faiss_indexes/index_faiss_mapping_layer3.json')
FAISS_MAPPING_PATH_LAYER2 = os.path.join(BASE_DIR, 'resources/faiss_indexes/index_faiss_mapping_layer2.json')

MODEL_STYLE_PATH = os.path.join(BASE_DIR, 'resources/model/model_state_dict.pth')